sudo: false

language: node_js
node_js:
  - 14

cache:
  directories:
    - node_modules
    - vendor

script:
  - make

deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    all_branches: true

addons:
  apt:
    update: true
